# Generated by Django 3.1.6 on 2021-03-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='product',
        ),
    ]
