# Generated by Django 3.1.6 on 2021-03-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='category',
        ),
        migrations.RemoveField(
            model_name='size',
            name='image',
        ),
        migrations.RemoveField(
            model_name='size',
            name='price',
        ),
        migrations.RemoveField(
            model_name='size',
            name='size',
        ),
        migrations.AddField(
            model_name='size',
            name='dimension',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
